version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A first hello"
      - run: sleep 5
      - run: touch raja
      - run: ls
  tag_test:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "tag hello"
      - run: sleep 5
      - run: ls

workflows:
  version: 2
  un-tagged-build:
    jobs:
      - build:
          filters:
            tags:
              ignore: /^v.*/
  tagged-build:
    jobs:
      - build:
          filters:
            tags:
              only: /^v.*/
      - tag_test:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
