version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A first hello"
      - run: sleep 25
  tag_test:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "tag hello"
      - run: sleep 25


workflows:
  version: 2
  build:
    jobs:
      - build
  build_n_branch_test:
    jobs:
      - tag_test:
          requires:
            - build
            tags:
              only: /v[0-9]+(\.[0-9]+)+/ # v1.2.3 only
